"""Dev-only preview: renders a handful of real mirrored messages to a static
HTML file so rendering output can be eyeballed in a browser before the forum
web app (ROADMAP.md §4) exists. Not part of the test suite or CI.

Uses a plain string template rather than Jinja -- Jinja isn't a project
dependency yet (that's §4's job) and this script's needs don't warrant
adding it early. Stable class names (.mention, .spoiler, .reaction-badge,
.reply-quote, .embed, .attachment) match what rendering/*.py already emits,
so the eventual theme CSS (DESIGN.md §5.9) is a drop-in against this same
markup.

Usage: uv run python scripts/render_preview.py [--limit N]
"""

import argparse
import asyncio
import os
from pathlib import Path

import psycopg
from dotenv import load_dotenv
from psycopg.rows import dict_row

from threadbare.db import queries
from threadbare.rendering.render_service import render_message_for_display

DEFAULT_LIMIT = 20
OUTPUT_PATH = Path(__file__).parent / "render_preview.html"

PAGE_TEMPLATE = """<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Threadbare rendering preview</title>
<style>
body {{ font-family: sans-serif; max-width: 700px; margin: 2rem auto; }}
.message {{ border: 1px solid #ccc; border-radius: 6px; padding: 1rem; margin-bottom: 1rem; }}
.message-author {{ font-weight: bold; }}
.reply-quote {{ border-left: 3px solid #999; padding-left: .5rem; color: #666; margin: .5rem 0; }}
.reactions {{ margin-top: .5rem; }}
.reaction-badge {{
    display: inline-block; border: 1px solid #ccc; border-radius: 10px;
    padding: .1rem .5rem; margin-right: .25rem;
}}
.embed {{
    border-left: 4px solid var(--embed-color, #ccc); padding: .5rem;
    margin-top: .5rem; background: #f7f7f7;
}}
img.emoji {{ height: 1.2em; vertical-align: middle; }}
</style>
</head>
<body>
<h1>Threadbare rendering preview</h1>
<p>{count} messages, most recent first (weighted toward richer content). Generated by
scripts/render_preview.py -- attachment images will often 404 (cached_url expiry, no
proxy yet; see ROADMAP.md §4).</p>
{messages}
</body>
</html>
"""

MESSAGE_TEMPLATE = """<article class="message" id="post-{id}">
<div class="message-author">{author}</div>
{reply_quote}
<div class="message-content">{content}</div>
{attachments}
{embeds}
{reactions}
</article>
"""


async def _fetch_candidate_ids(conn: psycopg.AsyncConnection, limit: int) -> list[int]:
    """Most recent messages, ordered to favor ones that exercise the most
    rendering features (attachment/embed/reaction/reply), so a small sample
    is actually useful to look at rather than mostly plain text.
    """
    async with conn.cursor() as cur:
        await cur.execute(
            """
            SELECT m.id
            FROM messages m
            LEFT JOIN attachments a ON a.message_id = m.id
            LEFT JOIN embeds e ON e.message_id = m.id
            LEFT JOIN reactions r ON r.message_id = m.id
            GROUP BY m.id
            ORDER BY
                (count(DISTINCT a.id) > 0)::int
                + (count(DISTINCT e.id) > 0)::int
                + (count(DISTINCT r.emoji) > 0)::int
                + (m.reply_to_id IS NOT NULL)::int DESC,
                m.posted_at DESC
            LIMIT %s
            """,
            (limit,),
        )
        rows = await cur.fetchall()
    return [row["id"] for row in rows]


async def render_preview(limit: int) -> int:
    load_dotenv()
    conn = await psycopg.AsyncConnection.connect(os.environ["DATABASE_URL"], row_factory=dict_row)
    try:
        message_ids = await _fetch_candidate_ids(conn, limit)
        sections = []
        for message_id in message_ids:
            message_row = await queries.get_message_for_render(conn, message_id)
            rendered = await render_message_for_display(conn, message_row)
            sections.append(
                MESSAGE_TEMPLATE.format(
                    id=message_row["id"],
                    author=message_row["author_display_name"],
                    reply_quote=rendered.reply_quote_html or "",
                    content=rendered.content_html,
                    attachments=rendered.attachments_html,
                    embeds=rendered.embeds_html,
                    reactions=rendered.reactions_html,
                )
            )
    finally:
        await conn.close()

    OUTPUT_PATH.write_text(PAGE_TEMPLATE.format(count=len(sections), messages="\n".join(sections)))
    return len(sections)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--limit", type=int, default=DEFAULT_LIMIT)
    args = parser.parse_args()

    count = asyncio.run(render_preview(args.limit))
    print(f"Wrote {count} rendered messages to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
